### ISSUE TITLE
Convert existing unit tests from Solidity to Javascript

### ISSUE THREAD

**Issue by GarethOates** [edgefund/edgefund-core#21]
I think we should consolidate all our tests into one language, and that language be JavaScript.  It's easier to work with, more flexible and we already have a couple of handy helper functions for interacting with and manipulating the blockchain.

**Comment by AndyWatt83** [comment]
I agree.

One counterpoint, that I read somewhere that is worth considering: Most Solidity functions are called by JavaScript from a UI of some kind, and so writing JavaScript tests is a valid representation of a real use case. But, solidity helper functions, which are called by other solidity functions may be tested in a more representative way with a solidity unit test. 

Food for thought, but I agree that tests should be JavaScript by default, and only in Solidity with a very good explanation as to why

**Comment by GarethOates** [comment]
OK yeah, that sounds fair.  So maybe the mock contract you're making just now, would be better served by Solidity tests whereas the CoinToss for example would still be Javascript.

I guess when we come to doing more security oriented tests, around making sure our contracts are resilient to reentry attacks for example, then Solidity is the only option, whereby the test contract would be the one trying to drain the funds, and we want to assert that it didn't succeed.

**Comment by GarethOates** [comment]
Hehe, ok yeah that sounds like a smart way forward

**Comment by GarethOates** [comment]
Closed by #30
