### ISSUE TITLE
Some additional dependencies are required to run coverage on windows

### ISSUE THREAD

**Issue by AndyWatt83** [edgefund/edgefund-core#22]
Running npm install on a windows machine requires that Python is installed. The error is:

gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.

To resolve this, open PowerShell in administrator mode and run:

npm install --global --production windows-build-tools
npm install --global node-gyp
setx PYTHON "%USERPROFILE%\.windows-build-tools\python27\python.exe"

(as per [these instructions](https://stackoverflow.com/questions/15126050/running-python-on-windows-for-node-js-dependencies))

**Comment by GarethOates** [comment]
I think we can just close this, it seems to be a symptom of running windows, and it's not a show stopper for just now I don't think?
